import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

const root = path.dirname(fileURLToPath(import.meta.url));

// Date/streak logic has to be exercised in a zone with DST transitions --
// set here so every worker process inherits it.
process.env.TZ = 'America/New_York';

export default defineConfig({
  resolve: {
    alias: {
      // The real virtual modules are generated by vite.config.ts plugins from
      // multi-megabyte data files; unit tests never need that data.
      'virtual:dictionary-data': path.join(root, 'src/test/virtualDictionaryData.ts'),
      'virtual:vocab-list-data': path.join(root, 'src/test/virtualText.ts'),
      'virtual:alwasit-data': path.join(root, 'src/test/virtualText.ts'),
    },
  },
  define: {
    __APP_VERSION__: JSON.stringify('test'),
  },
  test: {
    include: ['src/**/*.test.ts'],
    environment: 'node',
  },
});
