// Writes crowd-server/schema.sql from the statements the tests run, so the D1 database and the tests never differ.
//
//   node crowd-server/scripts/write-schema.mjs
//   wrangler d1 execute arabic-reader-crowd --file crowd-server/schema.sql
import { writeFileSync } from 'node:fs';
import { SCHEMA } from '../src/db.ts';

const text = '-- Generated by scripts/write-schema.mjs. Do not edit by hand.\n' + SCHEMA.map((s) => s + ';').join('\n') + '\n';
writeFileSync(new URL('../schema.sql', import.meta.url), text);
console.log(`Wrote schema.sql (${SCHEMA.length} statements)`);
